# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='\u80a1\u7968\u4ee3\u865f')),
                ('name', models.CharField(max_length=50, verbose_name='\u80a1\u7968\u540d\u7a31')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u4ea4\u6613\u65e5\u671f')),
                ('volume', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='\u6210\u4ea4\u91cf')),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=13, null=True, verbose_name='\u6210\u4ea4\u91d1\u984d')),
                ('opening_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='\u958b\u76e4\u50f9')),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='\u6536\u76e4\u50f9')),
                ('highest_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='\u6700\u9ad8\u50f9')),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='\u6700\u4f4e\u50f9')),
                ('price_diff', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='\u6f32\u8dcc')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', verbose_name='\u80a1\u7968\u4ee3\u865f')),
            ],
        ),
    ]
