# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='\u80a1\u7968\u4ee3\u865f'),
        ),
    ]
