# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20170628_1404'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('code', 'date')]),
        ),
    ]
